### ISSUE TITLE
dsigma output units and "little h"

### ISSUE THREAD

**Issue by JordanDucatel** [johannesulf/dsigma#8]
Hello,

I am using dsigma and am unsure about the units for the output since it does not seem to be written explicitly in the documentation. Does the units of the output table column 'ds', the excess surface density, include the dimensionless Hubble parameter 'little h'? (i.e. is the output in units of $M_{\odot}/pc^2$ or in units of $hM_{\odot}/pc^2$?)

Thank you very much for your help,

Jordan Ducatel

**Comment by johannesulf** [comment]
Hi Jordan, so sorry for not replying earlier. I must have missed this issue. To answer your question: the output does not include little h, i.e. it is in $M_\odot / \mathrm{pc}^2$. All calculations assume a cosmology and no correction for little h is being performed.

**Comment by JordanDucatel** [comment]
Great, thank you very much!
